### ISSUE TITLE
Building flatpaks with rpgp enabled

### ISSUE THREAD

**Issue by hpk42** [flathub/chat.delta.desktop#13]
Over at https://github.com/deltachat/deltachat-core/tree/master/python/wheelbuilder we now built with RPGP by default. The dockerfile shows the Rust setup and the buildwheels.sh shows how to instruct meson ("-Drpgp=true"), install RPGP and invoke the core building.  Flatpaks are currently the last missing release format missing RPGP ;)

**Comment by muelli** [comment]
I'm mildly confused.
Currently, the flatpak doesn't build deltachat-core itself. I guess that it's being built automatically by deltachat-desktop. So I'm wondering why this is now something the flatpak package has to actively do.

i would expect that deltachat-desktop either does not build deltachat-core itself or builds it in a way that it wants, i.e. with RPGP.

**Comment by hpk42** [comment]
@muelli oh ok. i am new to desktop building/releases :)

So here in this repo, only the following line needs to change?
https://github.com/flathub/chat.delta.desktop/blob/master/chat.delta.desktop.yml#L12://github.com/flathub/chat.delta.desktop/blob/master/chat.delta.desktop.yml#L120

**Comment by flub** [comment]
Apologies for missing this issue earlier.  I'm working on making dc-node not build/bundle dc-core itself (https://github.com/deltachat/deltachat-node/pulls) at which point it will become the responsibility of this repo to build with rpgp.  Hopefully that PR will make it very soon and then i'll update things here to cater for this.

**Comment by muelli** [comment]
FTR: I have pushed a beta branch with this commit: https://github.com/flathub/chat.delta.desktop/commit/6c5890b117a41709d5873beb98474ee7b8e39a61 which builds the https://github.com/deltachat/deltachat-desktop/releases/tag/v0.102.0-dev-rpgp release

**Comment by flub** [comment]
I'm surprised by that commit, it seems too easy since it doesn't add the rpgp lib to the flatpak build?  I may have missed something.

Anyway, -desktop really needs a new release for this which Jikstra started with a new draft but now they're not even sure they're going to release it because they might want to switch directly to deltachat-core-rust instead.  I'm confused myself and am just waiting to see what happens to the -desktop releases.

I also did a bunch of work in the -node package to no longer bundle all the things so if this release goes ahead some more deps should be built into the flatpak, essentially all deltachat-core deps as well as deltachat-core itself.

**Comment by muelli** [comment]
great. I'm looking forward to seeing this :)

**Comment by muelli** [comment]
I guess this is superseded by https://github.com/flathub/chat.delta.desktop/pull/23
