### ISSUE TITLE
Permission issue with attachments? 

### ISSUE THREAD

**Issue by hpk42** [flathub/chat.delta.desktop#14]
Seems some folks have issues with not being able to attach files from the host system. 

https://twitter.com/mjjzf/status/1107620941515902977

**Comment by muelli** [comment]
yes. That's another bucket of sand that Electron apps throw into your apps.
 [It doesn't use a native file picker widget](https://github.com/electron/electron/issues/2911).

We can relax the security of the sandbox and allow access to files. Telegram, for example, [allows xdg-download](https://github.com/flathub/org.telegram.desktop/blob/0e906c0c677a1b060ac356ab20e007ae94fa6582/org.telegram.desktop.json#L18). [Signal allows the home directory](https://github.com/flathub/org.signal.Signal/blob/ea0f6642e616a365562395624ffdeba9804ae325/org.signal.Signal.json#L18).
We could do something like that or give full (read) access to the host, if you want.

There seems to be [a patch here](https://github.com/electron/electron/pull/15293) and I think it'd be good to address this issue by getting that patch ready rather than working around the symptoms by relaxing the sandbox.

**Comment by muelli** [comment]
FTR: You can change the permissions yourself, if you feel so inclined, with something like
`flatpak --user  override --filesystem=home:rw chat.delta.desktop`

**Comment by flub** [comment]
I'd vote for doing the same as signal here.  Does dc-desktop also need to be able to write files?  Maybe something like `--filesystem=home:ro --filesystem=xdg-download:rw` would be sane/

**Comment by Simon-Laux** [comment]
> Does dc-desktop also need to be able to write files?

When you drag out files to save them or when you save them over the download button, it needs to write files.

**Comment by flub** [comment]
So you think restricting writing to the xdg-download dir is reasonable?  Or would you rather do exactly what signal does and make $HOMO read-write instead of read-only?  It's probably more intuitive for all of $HOME to be read-write as the other one is not really discoverable without UI help (and that probably won't happen as this is flatpak-specific)
