### ISSUE TITLE
why are we using rust-nightly to build core?

### ISSUE THREAD

**Issue by Simon-Laux** [flathub/chat.delta.desktop#80]
we don't need rust nightly I think we can just use the rust version we specify in the `rust-toolchain` file of the core repo. so 1.54.0 currently.

https://github.com/deltachat/deltachat-core-rust/blob/master/rust-toolchain

https://github.com/flathub/chat.delta.desktop/blob/e72fe3f656eedd33a2382463a69ca326e902a3c3/deltachat-core-rust.yaml#L25

using always the newest nightly version could break the build in the future.

**Comment by muelli** [comment]
This version of Rust is used:
https://github.com/flathub/chat.delta.desktop/blob/e72fe3f656eedd33a2382463a69ca326e902a3c3/deltachat-core-rust.yaml#L35
so that doesn't change in the future.

I guess it was required at one stage. Changing the version of Rust is as simple (or difficult) as changing those two lines. And yeah, I think using a non-nightly version sounds better.
